### ISSUE TITLE
Create endpoint for changing PAD ID

### ISSUE THREAD

**Issue by Gear61** [Gear61/PAD-Friend-Finder-Backend#1]
Takes in:
1. Current PAD ID
2. New PAD ID

I would make this a POST.

Returns:
200 (OK) - If new PAD is valid (no monsters in DB already with that ID)
400 (Bad Request) - If the new PAD ID already has monsters associated with it and this change would cause a monster box merge

Behavior: Just changes all the monsters with the old ID to have the new ID (update statement).

**Comment by jchio001** [comment]
I put it in get and I'm too lazy to change it. This should not matter though.
